import { useEffect, useMemo, useState } from "react"
import { useNavigate, useParams } from "react-router-dom"
import { observarCuenta } from "../services/cuentas"
import { observarMovimientos } from "../services/movimientos"
import { calcularMontoCierre, movimientosDeCaja, obtenerCaja, tipoMovimientoCaja } from "../services/cajas"

const pesos = new Intl.NumberFormat("es-AR", { style:"currency", currency:"ARS" }), fecha = new Intl.DateTimeFormat("es-AR", {day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false})
export default function CajaDetalle(){const {id,cajaId}=useParams(),navigate=useNavigate(),[cuenta,setCuenta]=useState(null),[caja,setCaja]=useState(null),[movimientos,setMovimientos]=useState([]),[error,setError]=useState("");useEffect(()=>{obtenerCaja(cajaId).then(setCaja).catch(()=>setError("No se pudo cargar la caja."));const a=observarCuenta(id,setCuenta,()=>setError("No se pudo cargar la cuenta.")),b=observarMovimientos(setMovimientos,()=>setError("No se pudieron cargar los movimientos."));return()=>{a();b()}},[cajaId,id]);const filtrados=useMemo(()=>caja?(caja.estado==="Cerrada"&&Array.isArray(caja.movimientoIds)?movimientos.filter((item)=>caja.movimientoIds.includes(item.id)):movimientosDeCaja(movimientos,id,caja)):[],[caja,id,movimientos]);if(!caja||!cuenta)return <div style={mensaje}>Cargando detalle...</div>;const cierre=caja.estado==="Abierta"?calcularMontoCierre(caja,filtrados,id):Number(caja.montoCierre||0);return <div style={pagina}><button onClick={()=>navigate(`/cuentas/${id}/caja`)} style={volver}>← Caja · {cuenta.nombre}</button><header style={cabecera}><div><span style={sobreTitulo}>DETALLE DE CAJA</span><h1 style={{margin:"3px 0"}}>{cuenta.nombre}</h1><small>{caja.estado}</small></div><strong style={{fontSize:27}}>{pesos.format(cierre)}</strong></header>{error&&<div style={errorBox}>{error}</div>}<section style={datos}><Dato label="Monto apertura" valor={pesos.format(Number(caja.montoApertura||0))}/><Dato label="Fecha de apertura" valor={fecha.format(caja.fechaApertura.toDate())}/><Dato label="Usuario apertura" valor={caja.abiertoPorNombre}/><Dato label="Monto cierre" valor={pesos.format(cierre)}/><Dato label="Fecha de cierre" valor={caja.fechaCierre?.toDate?fecha.format(caja.fechaCierre.toDate()):"—"}/><Dato label="Usuario cierre" valor={caja.cerradoPorNombre||"—"}/></section><section style={tablaBox}><h2 style={titulo}>Movimientos de {cuenta.nombre}</h2><div style={{overflowX:"auto"}}><table style={tabla}><thead><tr><th style={th}>Fecha</th><th style={th}>Tipo de movimiento</th><th style={th}>Concepto</th><th style={th}>Referencia</th><th style={th}>Monto</th></tr></thead><tbody>{filtrados.map((mov)=>{const tipo=tipoMovimientoCaja(mov,id);return <tr key={mov.id}><td style={td}>{mov.creadoEn?.toDate?fecha.format(mov.creadoEn.toDate()):mov.fecha?.toDate?fecha.format(mov.fecha.toDate()):"—"}</td><td style={td}><span style={tipo==="ingreso"?ingreso:egreso}>{tipo==="ingreso"?"Ingreso":"Egreso"}</span></td><td style={td}>{mov.concepto||mov.tipoMovimientoNombre||"—"}</td><td style={td}>{mov.eventoNombre||mov.descripcion||"—"}</td><td style={{...td,color:tipo==="ingreso"?"#16865c":"#b42339",fontWeight:700}}>{tipo==="ingreso"?"+ ":"− "}{pesos.format(Number(mov.monto||0))}</td></tr>})}{!filtrados.length&&<tr><td colSpan="5" style={mensaje}>No hay movimientos en este período.</td></tr>}</tbody></table></div></section></div>}
function Dato({label,valor}){return <div style={dato}><span>{label}</span><strong>{valor||"—"}</strong></div>};const pagina={maxWidth:1300,margin:"0 auto"},volver={marginBottom:12,padding:0,border:0,background:"transparent",color:"#4e2581",fontWeight:700,cursor:"pointer"},cabecera={display:"flex",justifyContent:"space-between",alignItems:"center",padding:"22px 25px",borderRadius:17,color:"white",background:"linear-gradient(100deg,#4e2581,#63349a)"},sobreTitulo={color:"#bfe8ff",fontSize:12,fontWeight:700,letterSpacing:".12em"},datos={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,margin:"18px 0"},dato={display:"flex",flexDirection:"column",gap:6,padding:15,border:"1px solid #e8e1ee",borderRadius:12,background:"white",color:"#4e2581"},tablaBox={overflow:"hidden",border:"1px solid #e8e1ee",borderRadius:15,background:"white"},titulo={margin:0,padding:"15px 18px",fontSize:18,color:"white",background:"linear-gradient(90deg,#4e2581,#63349a)"},tabla={width:"100%",borderCollapse:"collapse"},th={padding:13,textAlign:"left",background:"#f7f5fb",color:"#4b4058",fontSize:13},td={padding:13,borderTop:"1px solid #eee7f4",fontSize:13},ingreso={padding:"5px 9px",borderRadius:999,color:"#166534",background:"#dcfce7",fontWeight:700},egreso={...ingreso,color:"#991b1b",background:"#fee2e2"},mensaje={padding:30,textAlign:"center",color:"#776d83"},errorBox={margin:"14px 0",padding:12,borderRadius:10,background:"#fff1f2",color:"#be123c"}
