import { useEffect, useMemo, useState } from "react"
import { useNavigate, useParams } from "react-router-dom"
import { auth } from "../firebase"
import { useUserRole } from "../hooks/useUserRole"
import { observarCuenta } from "../services/cuentas"
import { observarMovimientos } from "../services/movimientos"
import { abrirCaja, calcularMontoCierre, cerrarCaja, movimientosDeCaja, observarCajasCuenta } from "../services/cajas"

const pesos = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS" })
const fecha = new Intl.DateTimeFormat("es-AR", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit", hour12: false })
const ahoraLocal = () => { const valor = new Date(); valor.setMinutes(valor.getMinutes() - valor.getTimezoneOffset()); return valor.toISOString().slice(0, 16) }

export default function CajaCuenta() {
  const { id } = useParams(), navigate = useNavigate(), { hasPermission } = useUserRole(auth.currentUser)
  const [cuenta, setCuenta] = useState(null), [cajas, setCajas] = useState([]), [movimientos, setMovimientos] = useState([])
  const [modal, setModal] = useState(""), [fechaOperacion, setFechaOperacion] = useState(ahoraLocal()), [montoApertura, setMontoApertura] = useState(""), [guardando, setGuardando] = useState(false), [error, setError] = useState("")
  useEffect(() => { const a = observarCuenta(id, setCuenta, () => setError("No se pudo cargar la cuenta.")); const b = observarCajasCuenta(id, setCajas, () => setError("No se pudieron cargar las cajas.")); const c = observarMovimientos(setMovimientos, () => setError("No se pudieron cargar los movimientos.")); return () => { a(); b(); c() } }, [id])
  const cajaAbierta = cajas.find((item) => item.estado === "Abierta")
  const movimientosAbiertos = useMemo(() => cajaAbierta ? movimientosDeCaja(movimientos, id, cajaAbierta, modal === "cerrar" && fechaOperacion ? new Date(new Date(fechaOperacion).getTime() + 59999) : new Date()) : [], [cajaAbierta, fechaOperacion, id, modal, movimientos])
  const montoCierre = cajaAbierta ? calcularMontoCierre(cajaAbierta, movimientosAbiertos, id) : 0

  async function confirmarApertura(e) {
    e.preventDefault(); const monto = Number(montoApertura)
    if (!Number.isFinite(monto) || monto < 0) return setError("Ingresá un monto de apertura válido.")
    setGuardando(true); setError("")
    try { await abrirCaja({ cuentaId: id, fechaApertura: fechaOperacion, montoApertura: monto, userId: auth.currentUser.uid }); setModal(""); setMontoApertura("") }
    catch (saveError) { console.error(saveError); setError(saveError.message === "caja-ya-abierta" ? "Esta cuenta ya tiene una caja abierta." : "No se pudo abrir la caja.") }
    finally { setGuardando(false) }
  }

  async function confirmarCierre(e) {
    e.preventDefault(); if (!cajaAbierta) return
    setGuardando(true); setError("")
    try { await cerrarCaja({ cuentaId: id, cajaId: cajaAbierta.id, fechaCierre: fechaOperacion, montoCierre, movimientoIds: movimientosAbiertos.map((item) => item.id), userId: auth.currentUser.uid }); setModal("") }
    catch (saveError) { console.error(saveError); setError(saveError.message === "fecha-cierre-invalida" ? "La fecha de cierre debe ser posterior a la apertura." : "No se pudo cerrar la caja.") }
    finally { setGuardando(false) }
  }

  if (!cuenta) return <div style={mensaje}>Cargando caja...</div>
  return <div style={pagina}><button onClick={() => navigate("/cuentas")} style={volver}>← Volver a cuentas</button><header style={cabecera}><div><span style={sobreTitulo}>CAJAS POR CUENTA</span><h1 style={{margin:"3px 0 0"}}>Caja · {cuenta.nombre}</h1></div>{hasPermission("cuentasAdministrar") && !cajaAbierta && <button onClick={() => { setFechaOperacion(ahoraLocal()); setMontoApertura(String(cuenta.saldoActual || 0)); setModal("abrir") }} style={botonPrincipal}>Nueva apertura</button>}</header>{error && <div style={errorBox}>{error}</div>}<section style={tablaBox}><div style={{overflowX:"auto"}}><table style={tabla}><thead><tr><th style={th}>Fecha de apertura</th><th style={th}>Fecha de cierre</th><th style={th}>Monto apertura</th><th style={th}>Monto cierre</th><th style={th}>Resultado</th><th style={th}>Abierto por</th><th style={th}>Cerrado por</th><th style={th}>Acciones</th></tr></thead><tbody>{cajas.map((caja) => <tr key={caja.id}><td style={td}>{caja.fechaApertura?.toDate ? fecha.format(caja.fechaApertura.toDate()) : "—"}</td><td style={td}>{caja.fechaCierre?.toDate ? fecha.format(caja.fechaCierre.toDate()) : "—"}</td><td style={td}>{pesos.format(Number(caja.montoApertura || 0))}</td><td style={td}>{pesos.format(Number(caja.montoCierre || 0))}</td><td style={{...td,color:Number(caja.resultado||0)>=0?"#16865c":"#b42339",fontWeight:700}}>{caja.estado === "Abierta" ? "Abierta" : pesos.format(Number(caja.resultado || 0))}</td><td style={td}>{caja.abiertoPorNombre || "—"}</td><td style={td}>{caja.cerradoPorNombre || "—"}</td><td style={td}><div style={acciones}><button onClick={() => navigate(`/cuentas/${id}/caja/${caja.id}`)} style={botonVer}>Ver</button>{caja.estado === "Abierta" && hasPermission("cuentasAdministrar") && <button onClick={() => { setFechaOperacion(ahoraLocal()); setModal("cerrar") }} style={botonCerrar}>Cerrar</button>}</div></td></tr>)}{!cajas.length && <tr><td colSpan="8" style={mensaje}>Esta cuenta todavía no tiene aperturas de caja.</td></tr>}</tbody></table></div></section>{modal === "abrir" && <Modal titulo="Apertura de caja" onClose={() => setModal("")}><form onSubmit={confirmarApertura}><Campo label="Fecha de apertura"><FechaHora24 value={fechaOperacion} onChange={setFechaOperacion} /></Campo><Campo label="Monto de apertura"><input type="number" min="0" step="1" value={montoApertura} onChange={(e) => setMontoApertura(e.target.value)} required /></Campo><Pie guardando={guardando} texto="Crear" /></form></Modal>}{modal === "cerrar" && <Modal titulo="Cierre de caja" onClose={() => setModal("")}><form onSubmit={confirmarCierre}><Campo label="Fecha de cierre"><FechaHora24 value={fechaOperacion} onChange={setFechaOperacion} /></Campo><div style={resumenCierre}><span>Monto de cierre calculado</span><strong>{pesos.format(montoCierre)}</strong><small>{movimientosAbiertos.length} movimientos desde la apertura</small></div><Pie guardando={guardando} texto="Cerrar caja" peligro /></form></Modal>}</div>
}

function Campo({label,children}) { return <label style={campo}><span>{label}</span>{children}</label> }
function FechaHora24({value,onChange}) { const [fechaValor="",horaCompleta=""] = value.split("T"), [hora="00",minuto="00"] = horaCompleta.split(":"); const horas=Array.from({length:24},(_,i)=>String(i).padStart(2,"0")), minutos=Array.from({length:60},(_,i)=>String(i).padStart(2,"0")); return <div style={fechaHora}><input type="date" value={fechaValor} onChange={(e)=>onChange(`${e.target.value}T${hora}:${minuto}`)} required/><select value={hora} onChange={(e)=>onChange(`${fechaValor}T${e.target.value}:${minuto}`)}>{horas.map((item)=><option key={item}>{item}</option>)}</select><span>:</span><select value={minuto} onChange={(e)=>onChange(`${fechaValor}T${hora}:${e.target.value}`)}>{minutos.map((item)=><option key={item}>{item}</option>)}</select><small>hs</small></div> }
function Pie({guardando,texto,peligro}) { return <div style={pie}><button disabled={guardando} style={peligro?botonCerrar:botonPrincipal}>{guardando?"Guardando...":texto}</button></div> }
function Modal({titulo,onClose,children}) { return <div style={fondo} onMouseDown={onClose}><section style={modal} onMouseDown={(e)=>e.stopPropagation()}><header style={modalHead}><h3 style={{margin:0}}>{titulo}</h3><button onClick={onClose} style={cerrar}>×</button></header>{children}</section></div> }
const pagina={maxWidth:1400,margin:"0 auto"},volver={marginBottom:12,padding:0,border:0,background:"transparent",color:"#4e2581",fontWeight:700,cursor:"pointer"},cabecera={display:"flex",justifyContent:"space-between",alignItems:"center",gap:15,padding:"20px 24px",borderRadius:"17px 17px 0 0",color:"white",background:"linear-gradient(100deg,#4e2581,#63349a)"},sobreTitulo={color:"#bfe8ff",fontSize:12,fontWeight:700,letterSpacing:".12em"},botonPrincipal={padding:"10px 16px",border:0,borderRadius:9,background:"#f4d00c",color:"#38145f",fontWeight:700,cursor:"pointer"},tablaBox={background:"white",border:"1px solid #e8e1ee",borderRadius:"0 0 17px 17px",overflow:"hidden"},tabla={width:"100%",borderCollapse:"collapse"},th={padding:12,textAlign:"left",background:"#f7f5fb",color:"#4b4058",fontSize:13,whiteSpace:"nowrap"},td={padding:12,borderTop:"1px solid #eee7f4",fontSize:13,whiteSpace:"nowrap"},acciones={display:"flex",gap:7},botonVer={padding:"8px 12px",border:0,borderRadius:7,color:"white",background:"#57b6ee",fontWeight:700,cursor:"pointer"},botonCerrar={padding:"8px 12px",border:0,borderRadius:7,color:"white",background:"#ef4444",fontWeight:700,cursor:"pointer"},mensaje={padding:30,textAlign:"center",color:"#776d83"},errorBox={margin:"14px 0",padding:12,borderRadius:10,background:"#fff1f2",color:"#be123c"},fondo={position:"fixed",inset:0,zIndex:1200,display:"grid",placeItems:"center",padding:18,background:"rgba(31,17,44,.55)"},modal={width:"min(500px,100%)",padding:22,borderRadius:16,background:"white",boxShadow:"0 24px 70px rgba(31,17,44,.3)"},modalHead={display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18,color:"#4e2581"},cerrar={border:0,background:"transparent",fontSize:26,color:"#665b71",cursor:"pointer"},campo={display:"flex",flexDirection:"column",gap:7,marginBottom:16,color:"#4b4058",fontWeight:700},fechaHora={display:"grid",gridTemplateColumns:"minmax(150px,1fr) 72px auto 72px auto",gap:7,alignItems:"center"},pie={display:"flex",justifyContent:"flex-end",marginTop:18},resumenCierre={display:"flex",flexDirection:"column",gap:6,padding:15,borderRadius:11,background:"#f7f5fb",color:"#4e2581"}
